pipeline {
    agent {
        docker { image 'node:16-alpine' }
    }

    stages {
        stage('Check Directory and Node Version') {
            steps {
                sh '''
                    echo "Current Directory:"
                    pwd
                    echo "Node.js Version:"
                    node --version
                '''
            }
        }
    }
}
