pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        
        sh 
        '''
        echo "current working directory"
        pwd
        echo "it displays the version of node js"
            node --version'''
      }
    }
  }
}
